version: "2.2"

services:
    mongo-db:
      image: "mongo"
      restart: "no"
      networks: ["rsk-network"]
      container_name: "mongo-db"
      ports:
        - "27017"
    lumino-explorer:
        #environment:
          #EXPLORER_API_URL: "http://explorer-api:8080/api/v1/" # this can use a dns name defined on hosts file to map to the final ip.
          #EXPLORER_PORT: 8080
          #RSK_ENDPOINT: "http://rsk-node:4444"
          #MONGO_DB_HOST: "mongo-db"
          #TOKEN_NETWORK_REGISTRY: 0xed8c9163F888Bc2f9C4F299325003DA5fC8676DD
        image: "lumino-testing-explorer-image:latest"
        restart: "no"
        networks: ["rsk-network"]
        container_name: "lumino-explorer"
        depends_on: ["mongo-db"]
        ports:
            - "8080"
networks:
  rsk-network:
    external: true

