#!/bin/bash

echo "Generating required images"
RSK_DOCKER_FOLDER="src/container-manager/docker-manager/docker-files/rsk-node"
RSK_IMAGE_NAME="rsk-node-image"
RSK_CORE_VERSION_CODENAME="PAPYRUS"
RSK_CORE_VERSION_NUMBER="2.2.0"
NETWORK_NAME="rsk-network"

function createMissingResources() {
    NETWORK=$(sudo docker network ls --filter name=${NETWORK_NAME} -q)
    if [ "${NETWORK}" == "" ]; then
        echo "Creating network ${NETWORK_NAME}"
        docker network create ${NETWORK_NAME}
    fi
}

createMissingResources

cd "${RSK_DOCKER_FOLDER}" || exit 1
docker build --build-arg RSK_CORE_VERSION_CODENAME=${RSK_CORE_VERSION_CODENAME} --build-arg RSK_CORE_VERSION_NUMBER=${RSK_CORE_VERSION_NUMBER} --no-cache -t "${RSK_IMAGE_NAME}" .
