#!/bin/bash

NETWORK=$3

if [ "" == "${NETWORK}" ]; then
	NETWORK=33
fi

TRUFFLE_CONFIG="module.exports = {  networks: { development: { host: 'rsk-node', port: 4444, network_id: '${NETWORK}' } } };"

ACCOUNT_ADDRESSES=$1

ETH_AMOUNT=$2

if [ "" == "${ACCOUNT_ADDRESSES}" ]; then
	echo "You need to specify at least one account address"
	exit -1
fi

if [ "" == "${ETH_AMOUNT}" ]; then
	ETH_AMOUNT=10
fi

echo ${TRUFFLE_CONFIG} >> truffle-config.js

cat > fundAccounts.js << EOF
module.exports = async function(callback) {
  const fundAccount = async function (accountAddress, amount) {
    const oldBalance = await web3.eth.getBalance(accountAddress);
    console.log('Old Balance', web3.utils.fromWei(oldBalance));
    const accounts = await web3.eth.getAccounts();
    await web3.eth.sendTransaction({from: accounts[0], to: accountAddress, value: web3.utils.toWei(amount, 'ether')});
    const balance = await web3.eth.getBalance(accountAddress);
    console.log('New Balance', web3.utils.fromWei(balance));
  }
  const addresses = '${ACCOUNT_ADDRESSES}'.split(',');
  for (const address of addresses) {
	console.log('Funding ' + address + ' with ${ETH_AMOUNT}');
    	await fundAccount(address, '${ETH_AMOUNT}');
  }
}
EOF

truffle exec fundAccounts.js

rm fundAccounts.js
rm truffle-config.js

echo "Funding accounts successfully completed"
