#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

if [ ! $(npx prettier --check .) ]; then
  npx prettier  --write --ignore-unknown .
  echo "Prettier found formatting error, fixing it, commit the changes again."
  exit 1
fi